# Generated by Django 3.2 on 2023-03-08 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolevoiceattribution',
            options={'verbose_name': '角色属性表', 'verbose_name_plural': '角色属性表'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1200, validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1'), django.core.validators.MaxValueValidator(4096, message='Value must be less than or equal to 4096')], verbose_name='ChatGPT对话最大token数'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_aivoice_speak_effect',
            field=models.CharField(blank=True, choices=[('robot', '机器人音效'), ('lolita', '萝莉音效'), ('lowpass', '低通音效'), ('echo', '回声音效'), ('lpfilter', '低通滤波器'), ('hpfilter', '高通滤波器')], max_length=255, verbose_name='角色音效'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_role',
            field=models.CharField(choices=[('zhimiao_emo', '知妙_多情感'), ('zhimi_emo', '知米_多情感'), ('zhiyan_emo', '知燕_多情感'), ('zhibei_emo', '知贝_多情感'), ('zhitian_emo', '知甜_多情感'), ('xiaoyun', '小云'), ('xiaogang', '小刚'), ('ruoxi', '若兮'), ('siqi', '思琪'), ('sijia', '思佳'), ('sicheng', '思诚'), ('aiqi', '艾琪'), ('aijia', '艾佳'), ('aicheng', '艾诚'), ('aida', '艾达'), ('ninger', '宁儿'), ('ruilin', '瑞琳'), ('siyue', '思悦')], default='zhimiao_emo', max_length=255, verbose_name='角色配音'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_speak_emotion',
            field=models.CharField(default='gentle', help_text='指定说话情绪。zhimiao_emo,zhimi_emo,zhiyan_emo,zhibei_emo,zhitian_emo', max_length=255, verbose_name='emotion标签感情'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_speak_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='指定情绪强度。默认值为1.0，表示预定义的情绪强度。最小值为0.01，导致目标情绪略有倾向。最大值为2.0，导致目标情绪强度加倍', max_digits=5, validators=[django.core.validators.MinValueValidator(-0.01, message='Value must be greater than or equal to -0.01'), django.core.validators.MaxValueValidator(2.0, message='Value must be less than or equal to 2.0')], verbose_name='emotion情绪强度'),
        ),
    ]
