# Generated by Django 3.2 on 2023-03-08 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0002_auto_20230309_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_speak_emotion',
            field=models.CharField(default='gentle', help_text='指定说话情绪。zhimiao_emo,zhimi_emo,zhiyan_emo,zhibei_emo,zhitian_emo', max_length=255, null=True, verbose_name='emotion标签感情'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_speak_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='指定情绪强度。默认值为1.0，表示预定义的情绪强度。最小值为0.01，导致目标情绪略有倾向。最大值为2.0，导致目标情绪强度加倍', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-0.01, message='Value must be greater than or equal to -0.01'), django.core.validators.MaxValueValidator(2.0, message='Value must be less than or equal to 2.0')], verbose_name='emotion情绪强度'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_random_weight',
            field=models.PositiveIntegerField(default=1, verbose_name='随机权重'),
        ),
    ]
