# Generated by Django 3.2 on 2023-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0004_auto_20230309_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=512, unique=True, verbose_name='jwt令牌'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户'),
        ),
    ]
