# Generated by Django 3.2 on 2023-03-09 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0006_auto_20230309_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolevoiceattribution',
            name='chatgpt_max_tokens',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1200, help_text='最大不超过4096', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1'), django.core.validators.MaxValueValidator(4096, message='Value must be less than or equal to 4096')], verbose_name='ChatGPT长对话最大token数'),
        ),
    ]
