# Generated by Django 3.2 on 2023-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0007_auto_20230309_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role',
            field=models.CharField(default='general', max_length=255, unique=True, verbose_name='角色'),
        ),
    ]
