# Generated by Django 3.2 on 2023-03-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0008_alter_rolevoiceattribution_system_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='RoleVoiceAttribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatgptapiv1.rolevoiceattribution'),
        ),
    ]
