# Generated by Django 3.2 on 2023-03-10 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0009_alter_blackbox_rolevoiceattribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_pitchrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-500, message='Value must be greater than or equal to -500'), django.core.validators.MaxValueValidator(500, message='Value must be less than or equal to 500')], verbose_name='语调'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_speechrate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-500, message='Value must be greater than or equal to -500'), django.core.validators.MaxValueValidator(500, message='Value must be less than or equal to 500')], verbose_name='语速'),
        ),
    ]
