# Generated by Django 3.2 on 2023-03-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0010_auto_20230310_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_role',
            field=models.CharField(choices=[('zhimiao_emo', '知妙_多情感'), ('zhimi_emo', '知米_多情感'), ('zhiyan_emo', '知燕_多情感'), ('zhibei_emo', '知贝_多情感'), ('zhitian_emo', '知甜_多情感'), ('xiaoyun', '小云'), ('xiaogang', '小刚'), ('ruoxi', '若兮'), ('siqi', '思琪'), ('sijia', '思佳'), ('sicheng', '思诚'), ('aiqi', '艾琪'), ('aijia', '艾佳'), ('aicheng', '艾诚'), ('aida', '艾达'), ('ninger', '宁儿'), ('ruilin', '瑞琳'), ('siyue', '思悦'), ('annie', 'Abby')], default='zhimiao_emo', max_length=255, verbose_name='角色配音'),
        ),
    ]
