# Generated by Django 3.2 on 2023-03-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0011_auto_20230313_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='parent',
            new_name='creator',
        ),
    ]
