# Generated by Django 3.2 on 2023-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0012_rename_parent_userinfo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=512, verbose_name='jwt令牌'),
        ),
    ]
