# Generated by Django 3.2 on 2023-03-16 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0013_alter_userinfo_jwt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolevoiceattribution',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role_alivoice_role',
            field=models.CharField(choices=[('zhimiao_emo', '知妙_多情感'), ('zhimi_emo', '知米_多情感'), ('zhiyan_emo', '知燕_多情感'), ('zhibei_emo', '知贝_多情感'), ('zhitian_emo', '知甜_多情感'), ('xiaoyun', '小云'), ('xiaogang', '小刚'), ('ruoxi', '若兮'), ('siqi', '思琪'), ('sijia', '思佳'), ('sicheng', '思诚'), ('aiqi', '艾琪'), ('aijia', '艾佳'), ('aicheng', '艾诚'), ('aida', '艾达'), ('ninger', '宁儿'), ('ruilin', '瑞琳'), ('siyue', '思悦'), ('aiya', '艾雅'), ('aixia', '艾夏'), ('aimei', '艾美'), ('aiyu', '艾雨'), ('aiyue', '艾悦'), ('aijing', '艾婧'), ('xiaomei', '小美'), ('aina', '艾娜'), ('yina', '伊娜'), ('sijing', '思婧'), ('sitong', '思彤'), ('xiaobei', '小北'), ('aitong', '艾彤'), ('aiwei', '艾薇'), ('aibao', '艾宝'), ('harry', 'Harry'), ('abby', 'Abby'), ('andy', 'Andy'), ('eric', 'Eric'), ('emily', 'Emily'), ('luna', 'Luna'), ('luca', 'Luca'), ('wendy', 'Wendy'), ('william', 'William'), ('olivia', 'Olivia'), ('lydia', 'Lydia'), ('annie', 'Annie'), ('ava', 'ava'), ('becca', 'Becca'), ('jiajia', '佳佳'), ('taozi', '桃子'), ('shanshan', '姗姗'), ('lydia', 'Lydia'), ('chuangirl', '小玥'), ('aishuo', '艾硕'), ('qingqing', '青青'), ('cuijie', '翠姐'), ('xiaoze', '小泽'), ('dahu', '大虎'), ('laotie', '老铁'), ('laomei', '老妹'), ('aikan', '艾侃'), ('kelly', 'Kelly'), ('tomoka', '智香'), ('tomoya', '智也'), ('Kyong', 'Kyong'), ('masha', 'masha'), ('guijie', '柜姐'), ('stella', 'Stella'), ('stanley', 'Stanley'), ('kenny', 'Kenny'), ('rosa', 'Rosa'), ('mashu', '马树'), ('xiaoxian', '小仙'), ('yuer', '悦儿'), ('maoxiaomei', '猫小美'), ('jielidou', '杰力豆'), ('maoxiaomei', '猫小美'), ('maoxiaomei', '猫小美'), ('maoxiaomei', '猫小美'), ('aifei', '艾飞'), ('yaqun', '亚群'), ('qiaowei', '巧薇'), ('ailun', '艾伦'), ('zhimao', '知猫'), ('zhiyuan', '知媛'), ('zhigui', '知柜'), ('zhiya', '知雅'), ('zhiyue', '知悦'), ('zhishuo', '知硕'), ('zhida', '知达'), ('zhistella', '知莎')], default='zhimiao_emo', max_length=255, verbose_name='角色配音'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('LimitedTime_UnlimitedRequest', '限时不限请求次数'), ('UnlimitedTime_LimitedRequest', '不限时限请求次数'), ('superuser', '超级用户')], help_text='只有超级管理员才能创建超级用户', max_length=255, null=True, verbose_name='客户类型'),
        ),
    ]
