# Generated by Django 3.2 on 2023-03-16 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0014_auto_20230317_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolevoiceattribution',
            name='shart_with_subadmin',
            field=models.BooleanField(default=False, verbose_name='是否与其他管理员共享'),
        ),
        migrations.AlterField(
            model_name='blackbox',
            name='RoleVoiceAttribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatgptapiv1.rolevoiceattribution', verbose_name='角色属性'),
        ),
        migrations.AlterField(
            model_name='blackbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='角色创建者'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户创建者'),
        ),
    ]
