# Generated by Django 3.2 on 2023-03-17 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0015_auto_20230317_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolevoiceattribution',
            name='chatgpt_max_reponse_tokens',
            field=models.PositiveIntegerField(default=400, help_text='最大不超过4096', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1'), django.core.validators.MaxValueValidator(4096, message='Value must be less than or equal to 4096')], verbose_name='ChatGPT单次回复最大token'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='shart_with_subadmin',
            field=models.BooleanField(default=False, help_text='勾选后，其他管理员可以看到这个角色', verbose_name='公共角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1200, help_text='最大不超过4096', validators=[django.core.validators.MinValueValidator(1, message='Value must be greater than or equal to 1'), django.core.validators.MaxValueValidator(4096, message='Value must be less than or equal to 4096')], verbose_name='ChatGPT保持长对话最大token数'),
        ),
    ]
