# Generated by Django 3.2 on 2023-03-17 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0017_auto_20230317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='RoleVoiceAttribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='chatgptapiv1.rolevoiceattribution', verbose_name='角色属性'),
        ),
        migrations.AlterField(
            model_name='blackbox',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
