# Generated by Django 3.2 on 2023-03-17 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0018_auto_20230318_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='RoleVoiceAttribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptapiv1.rolevoiceattribution', verbose_name='角色属性'),
        ),
        migrations.AlterField(
            model_name='blackbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='角色创建者'),
        ),
    ]
