# Generated by Django 3.2 on 2023-04-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0021_auto_20230418_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolevoiceattribution',
            name='avatar',
            field=models.ImageField(default='adai.png', upload_to='images/', verbose_name='角色头像'),
        ),
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='system_role',
            field=models.CharField(default='general', help_text='取名规则：角色名-账号名', max_length=255, unique=True, verbose_name='角色'),
        ),
    ]
