# Generated by Django 3.2 on 2023-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0022_auto_20230420_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolevoiceattribution',
            name='avatar',
            field=models.ImageField(default='images/adai.png', upload_to='images/', verbose_name='角色头像'),
        ),
    ]
