# Generated by Django 3.2 on 2024-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptapiv1', '0025_auto_20230505_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackbox',
            name='GPT_model_name',
            field=models.CharField(default='gpt-4o-mini', max_length=64, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='GPT_4_8K',
            field=models.BooleanField(default=False, verbose_name='GPT4o_128k开通'),
        ),
    ]
